### ISSUE TITLE
It looks like the latest on npmjs is outdated.

### ISSUE THREAD

**Issue by lipis** [mafintosh/electron-prebuilt#73] opened 2015-11-27 19:22 UTC
https://www.npmjs.com/package/electron-prebuilt

<img width="356" alt="screen shot 2015-11-27 at 20 22 25" src="https://cloud.githubusercontent.com/assets/125676/11447336/98a0dae4-9544-11e5-8b79-06e1c28fafa5.png">

**Comment by kevin-smets** [comment] 2015-11-27 21:48
Dupe of #71

**Closed** 2015-11-27 21:49 UTC
