### ISSUE TITLE
Interrupted install leaves cache corrupted

### ISSUE THREAD

**Issue by federicobond** [mafintosh/electron-prebuilt#25] opened 2015-05-10 05:11 UTC
This happens because it attempts to extract a zip file that has only been partially downloaded. We should support download resume or clear the cache if the install was interrupted. I believe the second would be more in line with user expectations.

Either way, I believe it should be more transparent about the fact that we it's creating a cache directory in `~/.electron`. Even though I suspected my problem involved caching, I had to dig into the code to find out where this cache was.

````
> electron-prebuilt@0.25.3 install /Users/federicobond/code/forks/electron-prebuilt
> node install.js

/Users/federicobond/code/forks/electron-prebuilt/install.js:18
  throw err
        ^
Error: end of central directory record signature not found
    at /Users/federicobond/code/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:98:14
    at /Users/federicobond/code/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:342:5
    at /Users/federicobond/code/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
````

**Comment by RnbWd** [comment] 2015-05-10 05:41
hmmm... @mafintosh any suggestions? I have some ideas

**Comment by RnbWd** [comment] 2015-05-10 05:45
temporary solution is deleting the `.electron` folder in your home directory until this issue is fixed (I'll submit a PR tonight)

**Comment by RnbWd** [comment] 2015-05-10 05:46
And it should be documented..

**Comment by federicobond** [comment] 2015-05-10 06:07
I did found out about the cache directory and deleted it, but only after looking at the code. A possible solution is to catch the `SIGINT` signal and, if process was downloading a file, remove it before exiting.

**Comment by federicobond** [comment] 2015-05-10 06:08
Then remove the `.electron` directory if it's empty.

**Comment by RnbWd** [comment] 2015-05-10 06:42
Quick fix submitted here: https://github.com/mafintosh/electron-prebuilt/pull/26

`.electron

**Comment by RnbWd** [comment] 2015-05-10 06:44
potential solution would be downloading zip in tmp dir before migrating to cache

**Comment by federicobond** [comment] 2015-05-10 06:58
Right. I meant removing the `.electron` directory *after* an interrupted install, if no other files remain in the cache.

**Comment by RnbWd** [comment] 2015-05-10 06:58
Just submitted another commit that should solve this issue completely. https://github.com/mafintosh/electron-prebuilt/pull/26

Unfortunately I'm not an official collaborator so I can't automatically merge the PR

**Comment by RnbWd** [comment] 2015-05-10 07:00
Interrupted downloads should actually resume progress where they left off - any error will completely remove the cache just in case

**Comment by federicobond** [comment] 2015-05-10 15:58
I disagree. As I stated above, I believe the expectation after an interrupted install (not due to network failure, but user sending `SIGINT` signal) is to clear the cache. The user never consented to a finished installation and therefore we should avoid leaving garbage in their home directory.

The network failure case might require another handling, where we notify the user that we lost connection and that he may resume the download afterwards.

**Comment by maxogden** [comment] 2015-05-10 19:16
before we bikeshed too much lets let @mafintosh weigh in :)

**Comment by mafintosh** [comment] 2015-05-10 20:27
I think we should change it to

1. if zip is in cache, copy it to the package and we're done
2. else download the zip to a deterministically named tmp file (this allows nugget to support resume etc)
3. on success move the tmp zip to `.electron` and goto 1

@RnbWd wanna update your PR to do something similar to the above?

**Comment by RnbWd** [comment] 2015-05-10 20:56
yes sounds like the best solution, I'll submit a PR later today

**Comment by RnbWd** [comment] 2015-05-10 22:04
@mafintosh you reintroduced the regression!!

**Comment by RnbWd** [comment] 2015-05-10 22:05
Sorry, meant to say:

@maxogden, you reintroduced the regression to this error!! I'll comment in `electron-download`

**Comment by mafintosh** [comment] 2015-05-12 21:22
So I'm assuming this is fixed now since the referenced issue got fixed in electron-download?

**Comment by RnbWd** [comment] 2015-05-12 21:50
I think it's fixed, @maxogden implemented most of it, but initially electron-download had the same behavior. So there was a small window where people could have potentially corrupted cache, and they'll need to delete it. But it should be fixed.

**Comment by mafintosh** [comment] 2015-05-12 22:00
:+1:

**Closed by mafintosh** 2015-05-12 22:00 UTC

**Comment by federicobond** [comment] 2015-05-12 22:48
Great! :+1:
